### ISSUE TITLE
Определиться со схемой БД

### ISSUE THREAD

**Issue by Minyewoo** [Minyewoo/ml-xraylab#5]

**Comment by kchpomp** [comment]
Есть ли у вас какие-то черновики БД или что-то подобное? Что вообще нужно? Какие роли?

**Comment by Minyewoo** [comment]
@kchpomp,
Вот примерная схема БД:
<img width="818" alt="image" src="https://user-images.githubusercontent.com/31701329/199072111-91b67b83-520b-4766-8f3f-7eedfe930096.png">

По ролям пока пусть будет Admin и Base.

Соответственно, нужны запросы для создания, редактирования, удаления и получения всех этих сущностей.
Удалять юзеров и роли может только админ.
Получать список всех юзеров может только админ.

**Comment by Minyewoo** [comment]
Для авторизации можешь добавить нужные поля юзеру, если понадобится

**Comment by kchpomp** [comment]
Окей, я понял, а я правильно понимаю, что, получается в snapshots хранятся не фотогрфии, а только ссылка на фото? Conclusion - это, получается, результат/диагноз?

**Comment by Minyewoo** [comment]
Насчёт фото всё правильно.
В conclusion будет просто храниться заметка врача. Поле может быть пустым.

**Comment by Minyewoo** [comment]
Надо ещё к снимку прикреплять как-то вероятности заболеваний. Предлагаю использовать документоориентированную БД, и у снимка в каком-нибудь поле (назовём его probabilities) хранить словарь такого вида:
```
{
    "заболевание1": 0.3,
    "заболевание2": 0.1,
    ...
}
```

**Comment by Minyewoo** [comment]
По поводу создания снимков:
В запросе помимо прочих данных будет прилетать файл снимка, тебе нужно будет сохранить его на файл-сервере, а в бд положить ссылку для доступа к этому изображению через файл-сервер.

Т.е. тебе нужно будет ещё и файл-сервер на бэке развернуть.

**Comment by kchpomp** [comment]
Bruh, никогда такого не делал, попробую разобраться.

**Comment by Minyewoo** [comment]
Ну, на голанге практически во всех рутинг-фреймворках (например, в gorilla mux) файл-сервер в одну строчку подключается.

**Comment by kchpomp** [comment]
а сколько вариантов диагноза может быть? Я лучше запихаю в mysql все наверно и создам колонок несколько или что-то в таком роде

**Comment by Minyewoo** [comment]
Подразумевалось, что диагноз будет руками вписывать сам пользователь (врач), поэтому вариантов бесконечное множество.
